class Parameters:
    WIDTH = 600
    HEIGHT = 800

    CIRCLE_SIZE = 5
    EXPLODE_RADIUS = 5

    GRAVITY = 0.01
    FIREWORK_GENERATION_CHANCE = 0.1

    MAX_TRAIL_SUB_PARTICLES = 5
    MAX_EXPLOSION_SUB_PARTICLES = 1

    EXPIRATION_TIME = 4
    EXPIRATION_TIMEDELTA = 0.01
